#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/Lesson_4_Assignment_Data_Manipulation_with_dplyr_Part_1.R /autograder/source/Lesson_4_Assignment_Data_Manipulation_with_dplyr_Part_1.R

cd /autograder/source


Rscript grade_one_submission.r 
